### ISSUE TITLE
Problem with connections 

### ISSUE THREAD

**Issue by lukazareba** [nfriess/carrier_infinity#3]
Hello

I've problem with connections

Info from log

Logger: homeassistant.components.climate
Source: custom_components/carrier_infinity/climate.py:532
Integration: Klimat (documentation, issues)
First occurred: 00:12:14 (1 occurrences)
Last logged: 00:12:14

Error while setting up carrier_infinity platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/carrier_infinity/climate.py", line 196, in setup_platform
    devices.append(_HTTPClientZone(_HTTPClient, zid, zone_name))
  File "/config/custom_components/carrier_infinity/climate.py", line 459, in __init__
    self.update()
  File "/config/custom_components/carrier_infinity/climate.py", line 532, in update
    self._current_temperature = float(get_safe(self.zone_status, "rt"))
TypeError: float() argument must be a string or a real number, not 'NoneType'

I use standard configuration

**Comment by lukazareba** [comment]
I want to mention that I do not use docker

**Comment by nfriess** [comment]
According to that error your thermostat is not sending the current temperature to HomeAssistant.  In order to debug this further I would need a capture of the data that it sending to HA.  For example capturing with Wireshark on the HA server would show us what data is going back and forth to be able to potentially make HA compatible with that thermostat.

**Comment by lukazareba** [comment]
Thanks but I don't know how to use it
